language: scala
dist: bionic
sudo: false
jdk: openjdk11
scala:
- 2.12.10
- 2.13.1

before_install:
- git fetch --tags
- ./make_harness.sh

stages:
- name: test
- name: release
  if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

script:
- sbt ++$TRAVIS_SCALA_VERSION test "e2e/test:runMain scalapb.validate.ScalaHarness"
- sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck

jobs:
  include:
  - stage: release
    script: sbt ci-release

cache:
  directories:
  - $HOME/.cache/bazel
  - $HOME/.cache/coursier
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
