name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Build test executor
      run: |
        ./make_harness.sh

    - uses: olafurpg/setup-scala@v5

    - name: Compile and test
      run: |
        sbt test "e2e/test:runMain scalapb.validate.ScalaHarness"

    - name: Formatting
      run: |
        sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
